### ISSUE TITLE
Panic when running example on window 10

### ISSUE THREAD

**Issue by bungcip** [tomaka/cpal#111]
Running example/enumerate.rs
I got panic like this:

thread '<main>' panicked at 'Unknown data format returned by GetMixFormat: 3', C:\Users\Gigih Aji Ibrahim.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.2.11\src\wasapi/mod.rs:197

running on windows 10, rustc 1.10.0-nightly (d91f8ab0f 2016-05-07)

**Comment by tomaka** [comment]
cc @retep998 

Did you publish that winapi fix yet?

**Comment by retep998** [comment]
`winapi = 0.2.7` has been published.

**Comment by tomaka** [comment]
@bungcip Running `cargo update` should fix the problem!

**Comment by bungcip** [comment]
Unfortunately, the problem still exist :cry: 
To make sure, I even create new blank project to test it again...
```
C:\depot>cargo new --bin enumerate

C:\depot>cd enumerate
<fill main.rs with content from enumerate.rs, add cpal = "*" to cargo.toml>

C:\depot\enumerate>cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling lazy_static v0.1.16
   Compiling ole32-sys v0.1.0
   Compiling winapi v0.2.7
   Compiling libc v0.2.11
   Compiling cpal v0.2.11
   Compiling enumerate v0.1.0 (file:///C:/depot/enumerate)

C:\depot\enumerate>target\debug\enumerate.exe
Endpoints:
1. Endpoint "{0.0.0.00000000}.{bf631a5a-b0db-44f4-bfca-e4f7b0f76e00}" Audio formats:
thread '<main>' panicked at 'Unknown data format returned by GetMixFormat: 3', C:\Users\Gigih Aji Ibrahim\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.2.11\src\wasapi/mod.rs:197
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore\result.rs:785

<..bla.bla..bla...>

```

**Comment by makufiru** [comment]
I just tested this on a fresh Win10 install and didn't experience this problem.

**Comment by tomaka** [comment]
Maybe @bungcip's error is legitimate?
The value `3` is `WAVE_FORMAT_IEEE_FLOAT`. This value is not documented and floats are handled through `WAVE_FORMAT_EXTENSIBLE`, but maybe it's some sort of weird corner case.

**Comment by bungcip** [comment]
After testing it again, I think I know the problem. This is because my wireless headset.

Running enumerate.exe without my wireless headet (SYNIC Wireless headset) attached, the program run without problem.
```
c:\depot\enumerate>cargo run
     Running `target\debug\enumerate.exe`
Endpoints:
1. Endpoint "{0.0.0.00000000}.{e8976dcb-9660-4667-8503-59c7d69af40f}" Audio formats:
1.1. Format { channels: [FrontLeft, FrontRight], samples_rate: SamplesRate(48000), data_type: F32 }
```
Now, I plug it again, the error happens again...
```
c:\depot\enumerate>cargo run
     Running `target\debug\enumerate.exe`
Endpoints:
1. Endpoint "{0.0.0.00000000}.{bf631a5a-b0db-44f4-bfca-e4f7b0f76e00}" Audio formats:
thread '<main>' panicked at 'Unknown data format returned by GetMixFormat: 3', C:\Users\Gigih Aji Ibrahim\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.2.11\src\wasapi/mod.rs:197
stack backtrace:
   0:     0x7ff7995273a2 - std::rt::lang_start::h61f4934e780b4dfc
   1:     0x7ff79952698d - std::rt::lang_start::h61f4934e780b4dfc
<bla .. bla.. bla>
```

**Comment by mitchmindtree** [comment]
I added handling of the `WAVE_FORMAT_IEEE_FLOAT` `wFormatTag` in #201 so this might have been fixed - @bungcip I know it's been a long time but any chance you could test this again?

**Comment by bungcip** [comment]
hi @mitchmindtree, I would love to test it again. However my SYNIC Wireless headset already broken

**Comment by mitchmindtree** [comment]
The #286 PR has removed the majority of `panic!`s that can occur within the synchronous API in favour of returning errors, so at the very least it should be possible to handle this now. Considering this and that #201 may have already fixed this, I'm going to close this for now. Feel free to re-open if you run into this again!
